servers:
    - protocol: socks5
      port: 1080
    - protocol: http(s)
      port: 2080

logging:
    level: debug
    folder: './log'

mtls_auth:
    enabled: on
    tls:
        versions: [1.2, 1.3]
    certificates:
        ca_cert: ca.pem
        server_cert: server-cert.pem
        private_key: server-key.pem